version: '3.8'

networks:
  sgt-network:

services:

  sgt_api:
    environment:
      PORT: 3000
      DB_HOST: sgt_db
      DB_PORT: 3306
      DB_DATABASE: sgt_db
      DB_USER: root
      DB_PASSWORD: sgtPass!123
      DB_POOL_MIN: 2
      DB_POOL_MAX: 10
      JWT_SECRET : elsecretodesgt
      COOKIE_EXP: 3d
    build:
      context: .
      dockerfile: ./build/api.Dockerfile
    container_name: sgt_api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    networks:
      - sgt-network
    
  sgt_db:
    image: mysql:8.0
    container_name: sgt_db
    environment:
      - MYSQL_DATABASE=sgt_db
      - MYSQL_ROOT_PASSWORD=sgtPass!123
    ports:
      - '3306:3306'
    networks:
      - sgt-network

  sgt_adminer:
    container_name: sgt_adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: sgt_db
    ports:
      - 8081:8080
    depends_on:
      -  sgt_db
    networks:
      - sgt-network